name: cnn
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - jupyterlab
  - pip
  - opencv
  - scikit-image
  - albumentations
  - pillow
  - pip:
      - tensorflow
      - httpx
