name: cnn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - scipy
  - scikit-image

  # Jupyter stack
  - jupyter
  - notebook
  - ipykernel
  - ipywidgets
  - pip:
      - tensorflow==2.15.0